### DISCUSSION TITLE
Is it possible to read translate secret from environment variable?

### DISCUSSION THREAD

**Discussion by p0deje** [Flinesoft/BartyCrouch#284] [Q&A]
I wonder if it's possible to configure `.bartycrouch.toml` to read the API key from an environment variable? I would hate to accidentally commit it to https://github.com/p0deje/Maccy/blob/master/.bartycrouch.toml. Something like this:

```toml
[update.translate]
translator = "deepL"
secret = ${DEEPL_TOKEN}
```
