### ISSUE TITLE
"Could not find a langCode for langCase 'english' when transforming translation"

### ISSUE THREAD

**Issue by blwinters** [Flinesoft/BartyCrouch#133]
I'm using BartyCrouch with SwiftGen and encountered this warning.

Here are the logs:
```
Starting Task 'Code Transform' ...
warning: BartyCrouch:  Could not find a langCode for langCase 'english' when transforming translation.
info: BartyCrouch:  Found translate entry with key 'alert.title.invalid_transaction' and 0 translations.
info: BartyCrouch:  Transformed 'BartyCrouch.translate(key: "alert.title.invalid_transaction", translations: [.english: "Invalid Transaction"])' to 'L10n.Alert.Title.invalidTransaction'.
Task 'Code Transform' took 18.449 seconds.
Starting Task 'Normalize' ...
Starting Task 'Lint' ...
```

And here is my BartyCrouch.swift file, where it specifies that English is supported.
```
enum BartyCrouch {
  enum SupportedLanguage: String {
    case english = "en"
    case french = "fr"
    case german = "de"
    case spanish = "es"
  }

  static func translate(key: String, translations: [SupportedLanguage: String], comment: String? = nil) -> String {
    let typeName = String(describing: BartyCrouch.self)
    let methodName = #function

    print(
      "Warning: [BartyCrouch]",
      "Untransformed \(typeName).\(methodName) method call found with key '\(key)' and base translations '\(translations)'.",
      "Please ensure that BartyCrouch is installed and configured correctly."
    )

    // fall back in case something goes wrong with BartyCrouch transformation
    return "BC: TRANSFORMATION FAILED!"
  }
}
```
Other details:
- English is the project's base language. 
- The Localizable.strings (English) has the autogenerated keys, but all values are empty strings.

It's not clear to me what caused this warning, any ideas?

**Comment by Dschee** [comment]
@blwinters Thank you for reporting this. Can you please look up for a second what `<lanc_code.lproj>` subfolders your project is holding with `Localizable.strings` files within? Is there one with `en.lproj` including a `Localizable.string` file? Other than that, all looks right to me ...

**Comment by alphatroya** [comment]
For me, the problem was in the previously moved helper method file. I've updated `supportedLanguageEnumPath` parameter for `update.transform` action and problem have gone.

**Comment by Jeehut** [comment]
Thank you @alphatroya, @blwinters could you please check if that helps you as well?

**Comment by noppefoxwolf** [comment]
Don't include another enum in directory for supportedLanguageEnumPath.
BartyCrouch has bug that load another enum such as SupportedLanguage.

**Comment by BrunoScheltzke** [comment]
The solution @alphatroya provided worked for me! I was having the same issue.

**Comment by blwinters** [comment]
Sorry that I haven't replied to this thread. I'm no longer involved in the relevant project, but glad that @alphatroya was able to come up with a solution.

**Comment by CavalcanteLeo** [comment]
I'm getting the same error:

`.bartycrouch.toml`:
```toml
[update]
tasks = ["interfaces", "code", "transform", "normalize"]

[update.interfaces]
defaultToBase = false
ignoreEmptyStrings = false
ignoreKeys = ["#bartycrouch-ignore!", "#bc-ignore!", "#i!"]
paths = ["."]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs"]
unstripped = false

[update.code]
additive = true
codePaths = ["."]
defaultToKeys = false
ignoreKeys = ["#bartycrouch-ignore!", "#bc-ignore!", "#i!"]
localizablePaths = ["."]
plistArguments = true
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs"]
unstripped = false

[update.transform]
codePaths = ["."]
localizablePaths = ["."]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs"]
supportedLanguageEnumPath = "."
transformer = "swiftgenStructured"
translateMethodName = "translate"
typeName = "BartyCrouch"

[update.normalize]
harmonizeWithSource = true
paths = ["."]
sortByKeys = true
sourceLocale = "en"
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs"]

[lint]
duplicateKeys = true
emptyValues = true
paths = ["."]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs"]
```

swiftgen
```yml
strings:
  inputs: LitiSaude/Resources/LocalizableStrings/en.lproj/Localizable.strings
  # inputs: LitiSaude/Resources/LocalizableStrings/en.lproj
  # filter: .+\.strings$
  outputs:
    - templateName: structured-swift5
      output: LitiSaude/Generated/Strings.swift
```

`BartyCrouch.swift`
```swift
import Foundation

enum BartyCrouch {
	enum SupportedLanguage: String {
		case english = "en"
		case portuguese = "pt-BR"
		case spanish = "es"
	}

	static func translate(key: String, translations: [SupportedLanguage: String], comment: String? = nil) -> String {
		let typeName = String(describing: BartyCrouch.self)
		let methodName = #function

		print(
			"Warning: [BartyCrouch]",
			"Untransformed \(typeName).\(methodName) method call found with key '\(key)' and base translations '\(translations)'.",
			"Please ensure that BartyCrouch is installed and configured correctly."
		)

		// fall back in case something goes wrong with BartyCrouch transformation
		return "BC: TRANSFORMATION FAILED!"
	}
}
```


error:
```
Starting Task 'Code Transform' ...
2022-05-25 03:26:47.400: ⚠️  Could not find a langCode for langCase 'english' when transforming translation.
2022-05-25 03:26:47.400: ⚠️  Could not find a langCode for langCase 'portuguese' when transforming translation.
2022-05-25 03:26:47.400: ℹ️  Found translate entry with key 'type-a-valid-email' and 0 translations.
2022-05-25 03:26:47.400: ℹ️  Transformed 'BartyCrouch.translate(
					key: "type-a-valid-email",
					translations: [
						.english: "type a valid email",
						.portuguese: "Digite um e-mail válido"
					],
					comment: "When the user types a wrong email (textfield hint)"
				 )' to 'L10n.typeAValidEmail'.
Task 'Code Transform' took 0.121 seconds.
Starting Task 'Normalize' ...
```
