### ISSUE TITLE
Localized Info.plist files are wiped

### ISSUE THREAD

**Issue by magneticrob** [Flinesoft/BartyCrouch#136]
Hey, I have just localized my Info.plist file, which requires creating a strings file called "InfoPlist.strings", clicking the localize button in Xcode, then filling it with strings in the corresponding languages in the following format:

`NSCalendarsUsageDescription = "This allows us to save the appointments you make.";`

Localization works correctly. Note that the key does not have quotes marks around it. If you run the BartyCrouch script as part of your build phases, these files are wiped.

This breaks the localization. I can have a look at this in depth when I have time, but in the meantime I have had to remove BartyCrouch from my project, if anyone is around to have a look I'd really appreciate it!

**Comment by magneticrob** [comment]
Just had a quick look at the repo and it looks like at some point perhaps an attempt was made to handle this situation, see here: https://github.com/Flinesoft/BartyCrouch/blob/b651fb970616a9739834cd2e7837e446b4786437/Sources/BartyCrouchKit/FileHandling/StringsFilesSearch.swift#L14

Although we declare a reference to the file as we should be avoiding it ("blacklistedStringFileNames"), it doesn't seem to actually be used anywhere

**Comment by Dschee** [comment]
Thanks for reporting this, it sure looks like something went wrong. I hope we can easily reproduce and fix it. Will have a look soonish – but feel free to drop a PR if you get the chance to fix it yourself. We probably had the same problem somewhere and started to fix it, as you can see in the code above. But why didn't finish it, I don't know. Maybe we found a workaround?

Maybe @fredpi can give more insight here?

**Comment by fredpi** [comment]
In a project of ours where we use BartyCrouch in conjunction with `Info.plist` Localizations, everything works fine – but I guess that's just because the `InfoPlist.strings` files are in a different folder (`"App/SupportingFiles"`) than the `Localizable.strings` files (`"App/Resources"`): A folder that's not parsed by BartyCrouch, as can be seen in the configuration.

### Configuration

Here's our `.bartycrouch.toml`:

```toml
[update]
tasks = ["interfaces", "transform", "normalize"]

[update.interfaces]
path = "App/Sources"

[update.transform]
codePath = "App/Sources"
localizablePath = "App/Resources"
transformer = "swiftgenStructured"
supportedLanguageEnumPath = "App/SupportingFiles"

[update.normalize]
path = "App"
sourceLocale = "de"

[lint]
path = "App"
```

### Workaround

Of course this issue should be fixed soon, but in the meantime you can probably work around it by moving the localizations into a folder that's not configured to be parsed by BartyCrouch.
